package org.apache.maven.doxia.sink;

import javax.swing.text.MutableAttributeSet;

public interface SinkEventAttributes extends MutableAttributeSet {
   String CLASS = "class";
   String ID = "id";
   String LANG = "lang";
   String STYLE = "style";
   String TITLE = "title";
   String PROFILE = "profile";
   String EMAIL = "email";
   String ALIGN = "align";
   String ALT = "alt";
   String BORDER = "border";
   String HEIGHT = "height";
   String HSPACE = "hspace";
   String ISMAP = "ismap";
   String SRC = "src";
   String USEMAP = "usemap";
   String VSPACE = "vspace";
   String WIDTH = "width";
   String NOSHADE = "noshade";
   String SIZE = "size";
   String NAME = "name";
   String CHARSET = "charset";
   String COORDS = "coords";
   String HREF = "href";
   String HREFLANG = "hreflang";
   String REL = "rel";
   String REV = "rev";
   String SHAPE = "shape";
   String TARGET = "target";
   String TYPE = "type";
   String BGCOLOR = "bgcolor";
   String CELLPADDING = "cellpadding";
   String CELLSPACING = "cellspacing";
   String FRAME = "frame";
   String RULES = "rules";
   String SUMMARY = "summary";
   String ABBRV = "abbrv";
   String AXIS = "axis";
   String COLSPAN = "colspan";
   String HEADERS = "headers";
   String NOWRAP = "nowrap";
   String ROWSPAN = "rowspan";
   String SCOPE = "scope";
   String VALIGN = "valign";
   String DECORATION = "decoration";
}
