package soot;

public interface PointsToAnalysis {
   String THIS_NODE = "THIS_NODE";
   int RETURN_NODE = -2;
   String THROW_NODE = "THROW_NODE";
   String ARRAY_ELEMENTS_NODE = "ARRAY_ELEMENTS_NODE";
   String CAST_NODE = "CAST_NODE";
   String STRING_ARRAY_NODE = "STRING_ARRAY_NODE";
   String STRING_NODE = "STRING_NODE";
   String STRING_NODE_LOCAL = "STRING_NODE_LOCAL";
   String EXCEPTION_NODE = "EXCEPTION_NODE";
   String RETURN_STRING_CONSTANT_NODE = "RETURN_STRING_CONSTANT_NODE";
   String STRING_ARRAY_NODE_LOCAL = "STRING_ARRAY_NODE_LOCAL";
   String MAIN_THREAD_NODE = "MAIN_THREAD_NODE";
   String MAIN_THREAD_NODE_LOCAL = "MAIN_THREAD_NODE_LOCAL";
   String MAIN_THREAD_GROUP_NODE = "MAIN_THREAD_GROUP_NODE";
   String MAIN_THREAD_GROUP_NODE_LOCAL = "MAIN_THREAD_GROUP_NODE_LOCAL";
   String MAIN_CLASS_NAME_STRING = "MAIN_CLASS_NAME_STRING";
   String MAIN_CLASS_NAME_STRING_LOCAL = "MAIN_CLASS_NAME_STRING_LOCAL";
   String DEFAULT_CLASS_LOADER = "DEFAULT_CLASS_LOADER";
   String DEFAULT_CLASS_LOADER_LOCAL = "DEFAULT_CLASS_LOADER_LOCAL";
   String FINALIZE_QUEUE = "FINALIZE_QUEUE";
   String CANONICAL_PATH = "CANONICAL_PATH";
   String CANONICAL_PATH_LOCAL = "CANONICAL_PATH_LOCAL";
   String PRIVILEGED_ACTION_EXCEPTION = "PRIVILEGED_ACTION_EXCEPTION";
   String PRIVILEGED_ACTION_EXCEPTION_LOCAL = "PRIVILEGED_ACTION_EXCEPTION_LOCAL";
   String PHI_NODE = "PHI_NODE";

   PointsToSet reachingObjects(Local var1);

   PointsToSet reachingObjects(Context var1, Local var2);

   PointsToSet reachingObjects(SootField var1);

   PointsToSet reachingObjects(PointsToSet var1, SootField var2);

   PointsToSet reachingObjects(Local var1, SootField var2);

   PointsToSet reachingObjects(Context var1, Local var2, SootField var3);

   PointsToSet reachingObjectsOfArrayElement(PointsToSet var1);
}
