package pxb.android;

public interface ResConst {
   int RES_STRING_POOL_TYPE = 1;
   int RES_TABLE_TYPE = 2;
   int RES_TABLE_PACKAGE_TYPE = 512;
   int RES_TABLE_TYPE_SPEC_TYPE = 514;
   int RES_TABLE_TYPE_TYPE = 513;
   int RES_XML_TYPE = 3;
   int RES_XML_RESOURCE_MAP_TYPE = 384;
   int RES_XML_END_NAMESPACE_TYPE = 257;
   int RES_XML_END_ELEMENT_TYPE = 259;
   int RES_XML_START_NAMESPACE_TYPE = 256;
   int RES_XML_START_ELEMENT_TYPE = 258;
   int RES_XML_CDATA_TYPE = 260;
}
